### PR TITLE
+ page contents

### PR DESCRIPTION
**Pull request by shawna-slh**

### CODE REVIEW

**Review by daniel-montalvo — COMMENTED** [review]
Thanks for the feedback.

It was a decision that @nitedog and I took to remove the table of contents. We think that in these short pages the table of contents would not be of much help since people could easily scheme the resource. Also, contents for the different sections are not very long, with the exception of the topics themselves. I guess people using small screens or mobile devices would benefit from having a TOC at the top, given that they would need to scroll to get to the content  below, so probably there we have a reason to bring it back. Any other reasons why you think TOC is necessary in this resource?

**Comment by shawna-slh** [comment]
Having Summary and Page Contents at the top of all WAI pages came from usability testing we did with the redesign a couple years ago. The default for WAI website resources is to include Summary and Page Contents -- **and** we are fine straying from the default when justified.

Personally, I really missed the Page Contents when going through these pages. I wanted to open each unit and look at the Page Contents to get an overview. I think some people would find the Page Contents useful.

At the same time, in the target user cases for this resource, users will probably dive in and spend a fair bit of time on these pages. For those users, the Page Contents is **not** needed to get an overview of the content. It might be useful for quickly jumping to a particular section.

Given the target use cases, I would be OK not having Page Contents on these pages.

**Comment by shawna-slh** [comment]
I *would* however, like a single list of the Units and Topics -- that would give the overview of the content. :-)

**Comment by shawna-slh** [comment]
Above comments hopefully helpful for @hidde when thinking about the navigation and design of the curricula. :-)

**Comment by daniel-montalvo** [comment]
We now have an outline of the current units in this module at https://w3c.github.io/wai-curricula/curricula/introduction/#units-in-this-module. It might need further details because now only units are listed there.

**Comment by shawna-slh** [comment]
> We now have an outline of the current units in this module at https://w3c.github.io/wai-curricula/curricula/introduction/#units-in-this-module. It might need further details because now only units are listed there.

Yup.

I think don't want to overwhelm it. Progressive disclosure would be good. Maybe we can use our expand-collapse code with a [Show Topics] button?

**Comment by shawna-slh** [comment]
Now that topics are included in the Intro page, that provides the outline I was missing.

**Pull request closed without merging**
